apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-aplicacion
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate      
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-contenedor
        image: ballesterosd/tp6:d6d1e8ed
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: appsettings-sealedsecret
          mountPath: /app/secrets/appsettings.json
      volumes:
      - name: appsettings-sealedsecret
        sealedSecret:
          name: my-app-secret          
      imagePullSecrets:
      - name: dockerhub-secret          
---
apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-service
spec:
  selector:
    app: mi-aplicacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mi-aplicacion-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mi-aplicacion
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-app-secret
  namespace: default
spec:
  encryptedData:
    appsettings.json: AgA/mcJWr53jXnWu/UI2gqboh1Z8NKosmqTnROVRI+kpVwWksIyws4ZmwRBHn28dEbH8p6P9Y74t/ES7SjKWotK9ttDpNg3+UzR+ZJrmoCFhGdbjsNPB3nJoSNfSjm9ab1avL2+D6+rJ9fhj63C0blBVPdgJwuoc/cTqhGkzre28XGz9+I7on7YOdEzKg2Pb4OSp5uAKQMKuUr+Z1Dru5aLG1L2a9qz4f1PYbY/fguKxDO/ItZibnD7fc7kfEe3l7vga5+uIDIk1Zz6Sh9+GYN4gX7kVSD797vfQ5O64v/3DW3IcoKibvruYsipJD+rz/YiG3pxM5Si/A4zxY1gZY4H9N5juUn1wAQqX/aY/+GtoUEH1GtVfP/Gi0O38P49GccLyUo5q5+TfhEHbH6sRIirwWXhemB9/dHVIQ59s8C9F7F2XeiZKq21XlD5UWGYiU6IepeZq7BVIxOQHr5wnjPoNfeXaYIxwZgZ/OkX8yGVogll70QpTnEq0NRRRa8ZKFW+WMrXH7tXGQGMcAf3h44pwyIT5aTYzKm+qz0SbZE+mnIi9kNAvJ1REAPTioybCUvFSITMD7S0IPnDIq3g/02+Z9U06Gd18OcuQx1FyPnNnWknFjnyomXi5pGh2kH6Ieqx6PF2rcRTA75o2ER+pUKXIajogaIcxtjJmkbkc7DzyvUutHW1kGLBICO0WGsyWTBiXPMpq2Za7jw/8ohCAmDHSwqe0B3HEPuPaWx+yiuwcgnr8/lbdtJZYEzfcZPFlVfFK7BmFQYRSsP40bzET0C9qJG66sLYT+AmIjZhqbTLoPBh8y1Ck9Avz4MkJTzIwU9puLNqeQyOu3DBcKRu4/ldP+8jnGF1fULkLg3QjLEJzRfoalu0b3XO5cHHtywIEbL5WpiuMBR5FfcwjXUOBHvV5h4iHWkE+mjlxYr/8zQok9hLns8+PlQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-app-secret
      namespace: default

